import type { AppVersion, AppManifest } from '@/types'
import { daysAgo } from './time'

interface Row {
  id: string
  appId: string
  version: string
  createdAt: string
  createdBy?: string
  sessionId?: string
  manifest: AppManifest
  handlerSource: string
  changeNote?: string
  isRollback?: boolean
  rolledBackFromVersionId?: string
}

function mk(row: Row): AppVersion {
  const { createdBy = 'u-samzong', ...rest } = row
  return { tenantId: 'acme', createdBy, ...rest }
}

function handlerStub(appName: string, version: string): string {
  return `// ${appName} — ${version}
// Generated by Forge runtime scaffolding.

import { defineApp } from '@forge/runtime'

export default defineApp({
  async run(ctx) {
    ctx.logger.info('${appName}: run start')
    const items = await ctx.data.list({ limit: 20 })
    for (const item of items) {
      ctx.logger.debug('processing', { id: item.id })
    }
    await ctx.notify.send({ channel: 'default', body: 'Run complete.' })
    return { processed: items.length }
  },
})
`
}

const manifests = {
  teamAlert: {
    runtimeIdentity: 'invoker' as const,
    capabilities: ['dce:alerts:read', 'dce:pods:read', 'dce:teams:read', 'feishu:messages:send'],
    schedule: '*/5 * * * *',
    triggers: [{ type: 'schedule' as const, config: { cron: '*/5 * * * *' } }],
    dataRetention: '30d' as const,
  },
  prReview: {
    runtimeIdentity: 'service-account' as const,
    capabilities: ['github:pulls:read', 'github:pulls:write', 'github:labels:write', 'feishu:messages:send'],
    triggers: [{ type: 'webhook' as const, config: { event: 'pull_request' } }],
    dataRetention: '90d' as const,
  },
  churn: {
    runtimeIdentity: 'invoker' as const,
    capabilities: ['crm:accounts:read', 'crm:signals:read', 'feishu:messages:send'],
    schedule: '0 9 * * *',
    triggers: [{ type: 'schedule' as const, config: { cron: '0 9 * * *' } }],
    dataRetention: '90d' as const,
  },
  bizCockpit: {
    runtimeIdentity: 'invoker' as const,
    capabilities: ['tf:customers:read', 'tf:sla:read', 'tf:billing:read', 'tf:audit:write'],
    dataRetention: '90d' as const,
  },
  weeklySales: {
    runtimeIdentity: 'invoker' as const,
    capabilities: ['crm:orders:read', 'crm:regions:read'],
    schedule: '0 9 * * MON',
    triggers: [{ type: 'schedule' as const, config: { cron: '0 9 * * MON' } }],
    dataRetention: '30d' as const,
  },
  k8sWatcher: {
    runtimeIdentity: 'service-account' as const,
    capabilities: ['dce:namespaces:watch', 'feishu:messages:send'],
    triggers: [{ type: 'event' as const, config: { source: 'k8s-api' } }],
    dataRetention: '7d' as const,
  },
  postmortem: {
    runtimeIdentity: 'invoker' as const,
    capabilities: ['dce:incidents:read', 'dce:audit:read'],
    dataRetention: 'none' as const,
  },
  slowQuery: {
    runtimeIdentity: 'service-account' as const,
    capabilities: ['mysql:slow-log:read', 'feishu:messages:send'],
    schedule: '0 6 * * *',
    dataRetention: '30d' as const,
  },
  migrationForm: {
    runtimeIdentity: 'invoker' as const,
    capabilities: ['forms:submit', 'sre:requests:write'],
    dataRetention: '90d' as const,
  },
  standup: {
    runtimeIdentity: 'service-account' as const,
    capabilities: ['github:issues:read', 'github:pulls:read', 'feishu:messages:send'],
    schedule: '30 9 * * 1-5',
    triggers: [{ type: 'schedule' as const, config: { cron: '30 9 * * 1-5' } }],
    dataRetention: '30d' as const,
  },
  sharedDefault: {
    runtimeIdentity: 'invoker' as const,
    capabilities: ['dce:data:read'],
    dataRetention: '30d' as const,
  },
} satisfies Record<string, AppManifest>

export const appVersionsSeed: AppVersion[] = [
  mk({
    id: 'ver-tad-1-0',
    appId: 'team-alert-dashboard',
    version: 'v1.0',
    createdAt: daysAgo(170),
    manifest: manifests.teamAlert,
    handlerSource: handlerStub('Team Alert Dashboard', 'v1.0'),
    changeNote: 'Initial release: weekly alerts aggregation + Feishu push.',
  }),
  mk({
    id: 'ver-tad-1-1',
    appId: 'team-alert-dashboard',
    version: 'v1.1',
    createdAt: daysAgo(120),
    manifest: manifests.teamAlert,
    handlerSource: handlerStub('Team Alert Dashboard', 'v1.1'),
    changeNote: 'Group alerts by pod and severity; reduce noise.',
  }),
  mk({
    id: 'ver-tad-1-2',
    appId: 'team-alert-dashboard',
    version: 'v1.2',
    createdAt: daysAgo(60),
    manifest: manifests.teamAlert,
    handlerSource: handlerStub('Team Alert Dashboard', 'v1.2'),
    changeNote: 'Switch to 5-minute refresh; add per-pod threshold config.',
  }),
  mk({
    id: 'ver-tad-1-2-1',
    appId: 'team-alert-dashboard',
    version: 'v1.2.1',
    createdAt: daysAgo(20),
    manifest: manifests.teamAlert,
    handlerSource: handlerStub('Team Alert Dashboard', 'v1.2.1'),
    changeNote: 'Rolled back from v1.3-experimental — false-positive regression.',
    isRollback: true,
    rolledBackFromVersionId: 'ver-tad-1-3-experimental',
  }),
  mk({
    id: 'ver-tad-1-3',
    appId: 'team-alert-dashboard',
    version: 'v1.3',
    createdAt: daysAgo(2),
    manifest: manifests.teamAlert,
    handlerSource: handlerStub('Team Alert Dashboard', 'v1.3'),
    changeNote: 'Apply threshold tuning post-rollback; add dry-run preview flag.',
  }),

  mk({
    id: 'ver-prb-1-0',
    appId: 'pr-review-bot',
    version: 'v1.0',
    createdAt: daysAgo(210),
    manifest: manifests.prReview,
    handlerSource: handlerStub('PR Review Bot', 'v1.0'),
    changeNote: 'MVP: AI summary comment on new PRs.',
  }),
  mk({
    id: 'ver-prb-1-2',
    appId: 'pr-review-bot',
    version: 'v1.2',
    createdAt: daysAgo(150),
    manifest: manifests.prReview,
    handlerSource: handlerStub('PR Review Bot', 'v1.2'),
    changeNote: 'Add Feishu integration and author mention routing.',
  }),
  mk({
    id: 'ver-prb-1-5',
    appId: 'pr-review-bot',
    version: 'v1.5',
    createdAt: daysAgo(90),
    manifest: manifests.prReview,
    handlerSource: handlerStub('PR Review Bot', 'v1.5'),
    changeNote: 'Multi-language diff support; deprecate inline-only suggestions.',
  }),
  mk({
    id: 'ver-prb-2-0',
    appId: 'pr-review-bot',
    version: 'v2.0',
    createdAt: daysAgo(45),
    manifest: manifests.prReview,
    handlerSource: handlerStub('PR Review Bot', 'v2.0'),
    changeNote: 'Auto-label suggestions based on file-path heuristics.',
  }),
  mk({
    id: 'ver-prb-2-0-1',
    appId: 'pr-review-bot',
    version: 'v2.0.1',
    createdAt: daysAgo(30),
    manifest: manifests.prReview,
    handlerSource: handlerStub('PR Review Bot', 'v2.0.1'),
    changeNote: 'Hotfix: label-prediction timeout on large monorepos.',
  }),
  mk({
    id: 'ver-prb-2-1',
    appId: 'pr-review-bot',
    version: 'v2.1',
    createdAt: daysAgo(6),
    manifest: manifests.prReview,
    handlerSource: handlerStub('PR Review Bot', 'v2.1'),
    changeNote: 'Reviewer-load balancing and weekend-queue deferral.',
  }),

  mk({
    id: 'ver-ccew-0-3',
    appId: 'customer-churn-early-warning',
    version: 'v0.3',
    createdAt: daysAgo(90),
    manifest: manifests.churn,
    handlerSource: handlerStub('Customer Churn Early Warning', 'v0.3'),
    changeNote: 'Prototype: daily CRM signal scan.',
  }),
  mk({
    id: 'ver-ccew-0-9',
    appId: 'customer-churn-early-warning',
    version: 'v0.9',
    createdAt: daysAgo(40),
    manifest: manifests.churn,
    handlerSource: handlerStub('Customer Churn Early Warning', 'v0.9'),
    changeNote: 'Churn scoring heuristic v2; top-20 panel.',
  }),
  mk({
    id: 'ver-ccew-0-9-1',
    appId: 'customer-churn-early-warning',
    version: 'v0.9.1',
    createdAt: daysAgo(18),
    manifest: manifests.churn,
    handlerSource: handlerStub('Customer Churn Early Warning', 'v0.9.1'),
    changeNote: 'Rollback: v1.0-beta signal weighting caused false alarms.',
    isRollback: true,
    rolledBackFromVersionId: 'ver-ccew-1-0-beta',
  }),
  mk({
    id: 'ver-ccew-1-0',
    appId: 'customer-churn-early-warning',
    version: 'v1.0',
    createdAt: daysAgo(4),
    manifest: manifests.churn,
    handlerSource: handlerStub('Customer Churn Early Warning', 'v1.0'),
    changeNote: 'GA: drill-down panels, trend charts, region filter.',
  }),

  mk({
    id: 'ver-bc-0-0-1',
    appId: 'biz-cockpit',
    version: 'v0.0.1',
    createdAt: daysAgo(8),
    manifest: manifests.bizCockpit,
    handlerSource: handlerStub('Biz Cockpit', 'v0.0.1'),
    changeNote: 'Skeleton scaffold generated from cockpit prompt.',
  }),
  mk({
    id: 'ver-bc-0-1',
    appId: 'biz-cockpit',
    version: 'v0.1',
    createdAt: daysAgo(1),
    manifest: manifests.bizCockpit,
    handlerSource: handlerStub('Biz Cockpit', 'v0.1'),
    changeNote: 'Add SLA widget and revenue settlement pane.',
  }),

  mk({
    id: 'ver-wsr-0-1',
    appId: 'weekly-sales-report',
    version: 'v0.1',
    createdAt: daysAgo(40),
    manifest: manifests.weeklySales,
    handlerSource: handlerStub('Weekly Sales Report', 'v0.1'),
    changeNote: 'First pass: weekly aggregation by region.',
  }),
  mk({
    id: 'ver-wsr-0-3',
    appId: 'weekly-sales-report',
    version: 'v0.3',
    createdAt: daysAgo(16),
    manifest: manifests.weeklySales,
    handlerSource: handlerStub('Weekly Sales Report', 'v0.3'),
    changeNote: 'CRM inbox delivery + summary template.',
  }),
  mk({
    id: 'ver-wsr-0-4',
    appId: 'weekly-sales-report',
    version: 'v0.4',
    createdAt: daysAgo(5),
    manifest: manifests.weeklySales,
    handlerSource: handlerStub('Weekly Sales Report', 'v0.4'),
    changeNote: 'Draft — iterate on region breakdown table.',
  }),

  mk({
    id: 'ver-knw-0-1',
    appId: 'k8s-ns-watcher',
    version: 'v0.1',
    createdAt: daysAgo(55),
    manifest: manifests.k8sWatcher,
    handlerSource: handlerStub('K8s Namespace Watcher', 'v0.1'),
    changeNote: 'Watch namespace resource anomalies and notify Feishu.',
  }),
  mk({
    id: 'ver-knw-0-2',
    appId: 'k8s-ns-watcher',
    version: 'v0.2',
    createdAt: daysAgo(30),
    manifest: manifests.k8sWatcher,
    handlerSource: handlerStub('K8s Namespace Watcher', 'v0.2'),
    changeNote: 'Filter system namespaces; reduce false positives.',
  }),

  mk({
    id: 'ver-ipd-0-1',
    appId: 'incident-postmortem-drafter',
    version: 'v0.1',
    createdAt: daysAgo(10),
    manifest: manifests.postmortem,
    handlerSource: handlerStub('Incident Postmortem Drafter', 'v0.1'),
    changeNote: 'Draft initial postmortem from incident timeline.',
  }),

  mk({
    id: 'ver-sqd-0-1',
    appId: 'slow-query-digest',
    version: 'v0.1',
    createdAt: daysAgo(70),
    manifest: manifests.slowQuery,
    handlerSource: handlerStub('Slow Query Digest', 'v0.1'),
    changeNote: 'Nightly top-5 slow query extraction.',
  }),
  mk({
    id: 'ver-sqd-0-2',
    appId: 'slow-query-digest',
    version: 'v0.2',
    createdAt: daysAgo(35),
    manifest: manifests.slowQuery,
    handlerSource: handlerStub('Slow Query Digest', 'v0.2'),
    changeNote: 'Add per-schema breakdown and avg execution time.',
  }),
  mk({
    id: 'ver-sqd-0-3',
    appId: 'slow-query-digest',
    version: 'v0.3',
    createdAt: daysAgo(12),
    manifest: manifests.slowQuery,
    handlerSource: handlerStub('Slow Query Digest', 'v0.3'),
    changeNote: 'Switch to streaming log reader — timeout on large datasets (failing).',
  }),

  mk({
    id: 'ver-mcf-1-0',
    appId: 'migration-checklist-form',
    version: 'v1.0',
    createdAt: daysAgo(180),
    manifest: manifests.migrationForm,
    handlerSource: handlerStub('Migration Checklist Form', 'v1.0'),
    changeNote: 'Migration plan intake form routed to SRE.',
  }),
  mk({
    id: 'ver-mcf-1-1',
    appId: 'migration-checklist-form',
    version: 'v1.1',
    createdAt: daysAgo(90),
    manifest: manifests.migrationForm,
    handlerSource: handlerStub('Migration Checklist Form', 'v1.1'),
    changeNote: 'Add rollback plan requirement; stakeholder sign-off gate.',
  }),

  mk({
    id: 'ver-dsb-1-0',
    appId: 'daily-standup-brief',
    version: 'v1.0',
    createdAt: daysAgo(220),
    manifest: manifests.standup,
    handlerSource: handlerStub('Daily Standup Brief', 'v1.0'),
    changeNote: 'Morning brief: new issues and merged PRs.',
  }),
  mk({
    id: 'ver-dsb-1-5',
    appId: 'daily-standup-brief',
    version: 'v1.5',
    createdAt: daysAgo(100),
    manifest: manifests.standup,
    handlerSource: handlerStub('Daily Standup Brief', 'v1.5'),
    changeNote: 'Include deploy events and on-call handoff.',
  }),
  mk({
    id: 'ver-dsb-2-0',
    appId: 'daily-standup-brief',
    version: 'v2.0',
    createdAt: daysAgo(10),
    manifest: manifests.standup,
    handlerSource: handlerStub('Daily Standup Brief', 'v2.0'),
    changeNote: 'Team-scoped filters; configurable Feishu target.',
  }),

  mk({
    id: 'ver-hlr-1-0',
    appId: 'hr-leave-request',
    version: 'v1.0',
    createdAt: daysAgo(260),
    createdBy: 'u-bo',
    manifest: manifests.sharedDefault,
    handlerSource: handlerStub('HR Leave Request', 'v1.0'),
    changeNote: 'Official release (DCE HR team).',
  }),

  mk({
    id: 'ver-ov-1-0',
    appId: 'oncall-viewer',
    version: 'v1.0',
    createdAt: daysAgo(150),
    createdBy: 'u-liv',
    manifest: manifests.sharedDefault,
    handlerSource: handlerStub('Oncall Rotation Viewer', 'v1.0'),
    changeNote: 'View oncall rotation by service.',
  }),

  mk({
    id: 'ver-drr-0-9',
    appId: 'design-review-rota',
    version: 'v0.9',
    createdAt: daysAgo(90),
    createdBy: 'u-liv',
    manifest: manifests.sharedDefault,
    handlerSource: handlerStub('Design Review Rota', 'v0.9'),
    changeNote: 'Weekly schedule + session drill-down.',
  }),

  mk({
    id: 'ver-kvco-1-4',
    appId: 'kv-cost-optimizer',
    version: 'v1.4',
    createdAt: daysAgo(70),
    createdBy: 'u-bo',
    manifest: manifests.sharedDefault,
    handlerSource: handlerStub('KV Cost Optimizer', 'v1.4'),
    changeNote: 'Reclaim proposal drafts with projected savings.',
  }),

  mk({
    id: 'ver-sft-2-3',
    appId: 'security-finding-triage',
    version: 'v2.3',
    createdAt: daysAgo(22),
    createdBy: 'u-bo',
    manifest: manifests.sharedDefault,
    handlerSource: handlerStub('Security Finding Triage', 'v2.3'),
    changeNote: 'Severity-based routing to GitHub issues.',
  }),
]
